export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_LEAD = "SET_CURRENT_LEAD";
export const LEAD_LOADING = "LEAD_LOADING";
export const LEAD_DELETE = "LEAD_DELETE";
export const USER_DELETE = "USER_DELETE";